project_id = "cuycosjchirgjmfczcle"

[functions.send-whatsapp]
verify_jwt = false

[functions.chat-assistant]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false

[functions.generate-ai-style]
verify_jwt = false

[functions.generate-ai-image]
verify_jwt = false
